const genres = [
    'Action',
    'Adventure',
    'Comedy',
    'Cooking',
    'Crime',
    'Demons',
    'Drama',
    'Ecchi',
    'Fantasy',
    'Game',
    'Gender Bender',
    'Harem',
    'Historical',
    'Horror',
    'Isekai',
    'Josei',
    'Magic',
    'Martial Arts',
    'Mature',
    'Mecha',
    'Medical',
    'Military',
    'Music',
    'Mystery',
    'One Shot',
    'Overpower',
    'Parodi',
    'Police',
    'Psychological',
    'Reincarnation',
    'Romance',
    'School',
    'School life',
    'Sci-fi',
    'Seinen',
    'Shotacon',
    'Shoujo',
    'Shoujo Ai',
    'Shounen',
    'Shounen Ai',
    'Slice of Life',
    'Sport',
    'Sports',
    'Super Power',
    'Supernatural',
    'Thriller',
    'Tragedy',
    'Urban',
    'Vampire',
    'Webtoons',
    'Yuri',
]

exports.genres = genres
